/* Sample data shown only in Demo mode (before an access key is saved). All people are fictional. */
window.DEMO_DATA = (function () {
  const d = (n) => { const t = new Date(); t.setDate(t.getDate() + n); return t.toISOString().slice(0, 10); };
  const campaigns = [
    { campaign_code: 'C001', campaign_name: 'Research Collaboration', relationship_type: 'Research Collaboration', daily_limit: 10, min_score: 60, active: true, sender_identity: 'academic' },
    { campaign_code: 'C002', campaign_name: 'Medical Tourism Research', relationship_type: 'Research Collaboration', daily_limit: 8, min_score: 60, active: true, sender_identity: 'academic' },
    { campaign_code: 'C003', campaign_name: 'Odisha B2B Travel Partners', relationship_type: 'B2B Business', daily_limit: 12, min_score: 55, active: true, sender_identity: 'business' },
    { campaign_code: 'C004', campaign_name: 'Hotel Suppliers', relationship_type: 'Supplier', daily_limit: 8, min_score: 55, active: true, sender_identity: 'business' },
    { campaign_code: 'C005', campaign_name: 'Academic Networking', relationship_type: 'Academic Networking', daily_limit: 8, min_score: 50, active: true, sender_identity: 'academic' }
  ];
  const base = (o) => Object.assign({
    email: '', email_status: 'none', country: 'India', city: '', organization_url: '', profile_notes: '', interests: '',
    connection_date: '', last_contact_date: '', last_contact_channel: '', last_contact_summary: '', next_followup_date: '',
    followup_count: 0, nurture_stage: 'none', last_intent: '', do_not_contact: false, pending_channel: '', pending_subject: '', pending_message: '',
    recommended_action: 'connect', msg_variant_1: '', msg_variant_2: '', msg_variant_3: ''
  }, o);
  const contacts = [
    base({ person_key: 'li:demo-ananya-mishra', full_name: 'Dr. Ananya Mishra', salutation: 'Dr. Mishra', linkedin_url: 'https://www.linkedin.com/in/demo-ananya-mishra', job_title: 'Associate Professor, Hospital Management', organization: 'Sample Institute of Health Sciences', city: 'Bhubaneswar', campaign_code: 'C002', relationship_type: 'Research Collaboration', relevance_score: 94, relationship_potential: 88, contact_confidence: 60, timing_score: 85, priority_score: 85, priority: 'A', status: 'READY_FOR_CONNECTION', added_on: d(-1),
      why_this_person: 'Recently published on international patient trust in Indian hospitals; direct overlap with your SOR-model medical tourism work.',
      msg_variant_1: 'Dr. Mishra, your recent paper on international patient trust caught my attention. My work applies the SOR model to medical tourism decisions, so I would value connecting.',
      msg_variant_2: 'Dr. Mishra, how are you measuring trust across hospital touchpoints in your study? I am working on a related scale and would be glad to connect.',
      msg_variant_3: 'Dr. Mishra, I research medical tourism in Odisha and follow your work on patient trust. Happy to connect.' }),
    base({ person_key: 'li:demo-rahul-verma', full_name: 'Rahul Verma', salutation: 'Rahul', linkedin_url: 'https://www.linkedin.com/in/demo-rahul-verma', job_title: 'Founder', organization: 'Sample Journeys Pvt Ltd', city: 'Pune', campaign_code: 'C003', relationship_type: 'B2B Business', relevance_score: 86, relationship_potential: 80, contact_confidence: 55, timing_score: 70, priority_score: 78, priority: 'B', status: 'READY_FOR_CONNECTION', added_on: d(-2),
      why_this_person: 'Sells Char Dham and Varanasi pilgrimage packages; no Odisha product listed yet, a natural fit for Puri and Konark add-ons.',
      msg_variant_1: 'Hi Rahul, I saw your pilgrimage circuits across North India. We run Puri, Konark and Bhubaneswar programmes as an Odisha DMC and would be glad to connect.',
      msg_variant_2: 'Hi Rahul, do your pilgrimage clients ever ask about Jagannath Puri? We handle ground services in Odisha and would enjoy connecting.',
      msg_variant_3: 'Hi Rahul, Odisha DMC here, focused on pilgrimage and cultural trips. Happy to connect.' }),
    base({ person_key: 'li:demo-meera-iyer', full_name: 'Prof. Meera Iyer', salutation: 'Prof. Iyer', linkedin_url: 'https://www.linkedin.com/in/demo-meera-iyer', job_title: 'Professor of Tourism Management', organization: 'Sample University', city: 'Chennai', campaign_code: 'C001', relationship_type: 'Research Collaboration', relevance_score: 72, relationship_potential: 70, contact_confidence: 50, timing_score: 40, priority_score: 64, priority: 'C', status: 'READY_FOR_CONNECTION', added_on: d(-3), recommended_action: 'follow',
      why_this_person: 'Works on destination image scales; relevant for scale development, but no recent activity to anchor a note.',
      msg_variant_1: 'Prof. Iyer, I work on scale development in tourism and have found your destination image work useful. Would be glad to connect.' }),
    base({ person_key: 'li:demo-sanjay-patnaik', full_name: 'Sanjay Patnaik', salutation: 'Sanjay', linkedin_url: 'https://www.linkedin.com/in/demo-sanjay-patnaik', job_title: 'Director of Sales', organization: 'Sample Sea View Resort, Puri', city: 'Puri', campaign_code: 'C004', relationship_type: 'Supplier', relevance_score: 90, relationship_potential: 82, contact_confidence: 70, timing_score: 60, priority_score: 81, priority: 'A', status: 'CONNECTION_SENT', added_on: d(-14), last_contact_date: d(-11), last_contact_channel: 'linkedin', last_contact_summary: 'Connection request sent (note 1)', next_followup_date: d(-1) }),
    base({ person_key: 'li:demo-kavita-rao', full_name: 'Dr. Kavita Rao', salutation: 'Dr. Rao', linkedin_url: 'https://www.linkedin.com/in/demo-kavita-rao', job_title: 'Assistant Professor', organization: 'Sample School of Hospitality', campaign_code: 'C005', relationship_type: 'Academic Networking', relevance_score: 70, relationship_potential: 75, contact_confidence: 50, timing_score: 55, priority_score: 66, priority: 'B', status: 'CONNECTED', added_on: d(-20), connection_date: d(-4), last_contact_date: d(-4), last_contact_channel: 'linkedin', last_contact_summary: 'Connection accepted', next_followup_date: d(-1), nurture_stage: 'welcome',
      pending_channel: 'linkedin', pending_message: 'Thank you for connecting, Dr. Rao. I noticed you are organising the hospitality education session at [conference name]. Is the call for papers still open? I have a short study on guest trust that might fit.' }),
    base({ person_key: 'li:demo-arjun-sethi', full_name: 'Arjun Sethi', salutation: 'Arjun', linkedin_url: 'https://www.linkedin.com/in/demo-arjun-sethi', job_title: 'Head of Contracting', organization: 'Sample Holidays', email: 'arjun@example.com', email_status: 'provided_unverified', campaign_code: 'C003', relationship_type: 'B2B Business', relevance_score: 88, relationship_potential: 85, contact_confidence: 80, timing_score: 90, priority_score: 87, priority: 'A', status: 'OPPORTUNITY', added_on: d(-30), connection_date: d(-21), last_contact_date: d(-2), last_contact_channel: 'linkedin', last_contact_summary: 'They replied: looking for an Odisha ground partner for winter FITs', last_intent: 'HIGH_OPPORTUNITY', next_followup_date: d(0), followup_count: 1,
      pending_channel: 'email', pending_subject: 'Odisha winter FIT rates and sample itinerary', pending_message: 'Hi Arjun,\n\nThanks for the quick reply. As promised, here is a 4-night Puri, Konark and Chilika sample itinerary with net rates for December to February: [attach itinerary].\n\nWould a 20-minute call on Thursday work to go through transfers and hotel options?\n\n[Your name]' }),
    base({ person_key: 'li:demo-fatima-khan', full_name: 'Fatima Khan', salutation: 'Fatima', linkedin_url: 'https://www.linkedin.com/in/demo-fatima-khan', job_title: 'International Patient Services Manager', organization: 'Sample Multispecialty Hospital', campaign_code: 'C002', relationship_type: 'Research Collaboration', relevance_score: 80, relationship_potential: 78, contact_confidence: 55, timing_score: 60, priority_score: 72, priority: 'B', status: 'ENGAGED', added_on: d(-40), connection_date: d(-33), last_contact_date: d(-6), last_contact_channel: 'linkedin', last_contact_summary: 'They replied: open to sharing anonymised survey access', last_intent: 'POSITIVE_OPPORTUNITY', next_followup_date: d(3), followup_count: 2 }),
    base({ person_key: 'li:demo-vikram-das', full_name: 'Vikram Das', salutation: 'Vikram', linkedin_url: 'https://www.linkedin.com/in/demo-vikram-das', job_title: 'General Manager', organization: 'Sample Heritage Hotel', campaign_code: 'C004', relationship_type: 'Supplier', relevance_score: 74, relationship_potential: 70, contact_confidence: 55, timing_score: 45, priority_score: 67, priority: 'B', status: 'NURTURE', added_on: d(-90), connection_date: d(-80), last_contact_date: d(-20), last_contact_channel: 'linkedin', last_contact_summary: 'Follow-up: shared Rath Yatra demand outlook', next_followup_date: d(10), followup_count: 3 }),
    base({ person_key: 'li:demo-neha-joshi', full_name: 'Neha Joshi', salutation: 'Neha', linkedin_url: 'https://www.linkedin.com/in/demo-neha-joshi', job_title: 'Product Manager', organization: 'Sample Trips', campaign_code: 'C003', relationship_type: 'B2B Business', relevance_score: 40, relationship_potential: 45, contact_confidence: 50, timing_score: 40, priority_score: 43, priority: 'C', status: 'NOT_RELEVANT', added_on: d(-10), why_this_person: 'Focuses on outbound Europe; no inbound India product.' }),
    base({ person_key: 'li:demo-rohan-mehta', full_name: 'Rohan Mehta', salutation: 'Rohan', linkedin_url: 'https://www.linkedin.com/in/demo-rohan-mehta', job_title: 'Owner', organization: 'Sample Travel House', campaign_code: 'C003', relationship_type: 'B2B Business', relevance_score: 78, relationship_potential: 72, contact_confidence: 50, timing_score: 50, priority_score: 70, priority: 'B', status: 'IGNORED', added_on: d(-35), last_contact_date: d(-30), last_contact_summary: 'Connection request not accepted' })
  ];
  const interactions = [
    { person_key: 'li:demo-arjun-sethi', full_name: 'Arjun Sethi', interaction_date: d(-2), channel: 'linkedin', direction: 'inbound', interaction_type: 'reply_received', intent: 'HIGH_OPPORTUNITY', message: 'We are looking for an Odisha ground partner for winter FITs. Can you share rates?' },
    { person_key: 'li:demo-arjun-sethi', full_name: 'Arjun Sethi', interaction_date: d(-9), channel: 'linkedin', direction: 'outbound', interaction_type: 'follow_up', message: 'Thanks for connecting, Arjun. Noticed you are expanding East India departures...' },
    { person_key: 'li:demo-arjun-sethi', full_name: 'Arjun Sethi', interaction_date: d(-21), channel: 'linkedin', direction: 'inbound', interaction_type: 'connection_accepted', message: '' },
    { person_key: 'li:demo-kavita-rao', full_name: 'Dr. Kavita Rao', interaction_date: d(-4), channel: 'linkedin', direction: 'inbound', interaction_type: 'connection_accepted', message: '' },
    { person_key: 'li:demo-fatima-khan', full_name: 'Fatima Khan', interaction_date: d(-6), channel: 'linkedin', direction: 'inbound', interaction_type: 'reply_received', intent: 'POSITIVE_OPPORTUNITY', message: 'Happy to help with survey access once you share the questionnaire.' },
    { person_key: 'li:demo-sanjay-patnaik', full_name: 'Sanjay Patnaik', interaction_date: d(-11), channel: 'linkedin', direction: 'outbound', interaction_type: 'connection_request', message: 'Sanjay, we contract Puri properties for our B2B partners and would be glad to connect.' },
    { person_key: 'li:demo-vikram-das', full_name: 'Vikram Das', interaction_date: d(-20), channel: 'linkedin', direction: 'outbound', interaction_type: 'follow_up', message: 'Sharing our Rath Yatra demand outlook for your planning.' }
  ];
  return { contacts, campaigns, interactions, generated_at: new Date().toISOString() };
})();
